### ISSUE TITLE
missing katpoint dependency

### ISSUE THREAD

**Issue by flyingfrog81** [ska-telescope/tmc-prototype#11] opened 2019-03-21 08:36 UTC
Trying the system on a vanilla docker setup, the dishleafnode errors out complaining about the missing katpoint module. 
`sys.path:  ['/app/tmcprototype/DishLeafNode/DishLeafNode', '/app/tmcprototype/DishLeafNode/DishLeafNode', '/venv/lib/python35.zip', '/venv/lib/python3.5', '/venv/lib/python3.5/plat-x86_64-linux-gnu', '/venv/lib/python3.5/lib-dynload', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/venv/lib/python3.5/site-packages']
Traceback (most recent call last):
  File "/app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py", line 34, in <module>
    import katpoint
ImportError: No module named 'katpoint'`

I think this dependency should be added to the Pipfile.

**Comment by jyotinpo** [comment] 2019-03-22 12:14
I have already added katpoint dependency in setup.py file for DishLeafNode package. Refer:
https://github.com/ska-telescope/tmc-prototype/blob/master/tmcprototype/DishLeafNode/setup.py

However, the Pipfile doesn't consist katpoint package. I am still wondering why it failed, shouldn't it check the setup.py file for DishLeafNode package and resolve the dependency?

**Comment by jyotinpo** [comment] 2019-04-09 11:59
Hi @flyingfrog81,

Are we good to close this issue?

**Comment by flyingfrog81** [comment] 2019-04-09 12:11
I do not have time to reproduce the behaviour right now. Can you confirm that the above reported error is not present on a fresh environment?

**Comment by jyotinpo** [comment] 2019-04-23 09:55
Yes, since we added the dependency now in the `Pipfile`, the issue is now resolved. It is working well in the fresh environment.

**Closed by jyotinpo** 2019-04-23 09:55 UTC
Labels: bug
